### ISSUE TITLE
界面风格・Gruvbox

### ISSUE THREAD

**Issue by ASC8384** [ASC8384/myRime#1]
因为没找到官方中文译名，我就随便写了一个：
```yaml
  preset_color_schemes:
    gruvbox:
      name: 扶风 / Gruvbox
      author: ASC_8384 <ASC_8384@foxmail.com>
      back_color: 0x282828
      border_color: 0x21201D
      text_color: 0x8499A8
      hilited_text_color: 0x282828
      hilited_back_color: 0x8499A8
      hilited_candidate_text_color: 0xC7F1FB
      hilited_candidate_back_color: 0x454950
      candidate_text_color: 0xB2DBEB
      comment_text_color: 0x748392
```
![图片](https://user-images.githubusercontent.com/29878345/109130969-47956800-778d-11eb-86e7-948d328765c7.png)
